server:
  port: 8082

spring:
  application:
    name: movie-movie
  datasource:
    url: jdbc:mysql://localhost:3308/movie_movie?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        username: nacos
        password: nacos

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

tmdb:
  api-key: aa62bd3ea4193fada85b63f9e7cae44b
  base-url: https://api.themoviedb.org/3
  image-base-url: https://image.tmdb.org/t/p/w500

logging:
  level:
    com.movie.movie: DEBUG
